-- INSERT INTO dogs (id, dogs_name, dogs_age, dogs_size, dogs_breed, dogs_sex)
-- VALUES (01, "Tator-Tot", 2, "Large 80lbs", "German Shepherd", "Female"),
--        (02, "Buttons", 5, "Small 5lbs", "Chihuahua", "Male"),
--        (03, "Henry", 3, "Large 65lbs", "Golden Retriever", "Female"),
--        (04, "Diesel", 1, "Large 50lbs", "Boxer mix", "Male"),
--        (05, "Honey", 4, "Medium 30lbs", "Beagle", "Female"),
--        (06, "Biscuit", 8, "small 7lbs", "Toy Poodle", "Female"),
--        (07, "Indigo", 2, "Large 65lbs", "PitBull mix", "Male"),
--        (08, "Sebastian", 3, "Medium 35lbs", "Basset Hound", "Male"),
--        (09, "Coco", 1, "small 10lbs", "Pug", "Female"),
--        (10, "Taco", 4, "Medium 30lbs", "Labrador Retriever", "Male"),
--        (11, "Zola", 10, "Medium 40lbs", "Mini Doodle", "Female")
--        (12, "Sage", 7, "Large 100lb", "Husky Mix", "Male");

-- INSERT INTO owners (id, owners_name, dogs_name)
--     (1, "Johnson Family", "Bucky"),
--     (2, "Smiths", "Lola"),
--     (3, "Terri", "Fizz"),
--     (4, "Jenna", "Peanut"),
--     (5, "Todd", "Kane");